import { describe, expect, it } from 'vitest';

import { applySecurityHeaders } from '$lib/server/security-headers';

describe('applySecurityHeaders', () => {
	it('enforces browser security headers without changing the response', async () => {
		const response = new Response('catalog', {
			status: 201,
			headers: {
				'X-Existing': 'preserved',
				'X-Frame-Options': 'SAMEORIGIN'
			}
		});

		const securedResponse = applySecurityHeaders(response);

		expect(securedResponse).toBe(response);
		expect(securedResponse.status).toBe(201);
		expect(await securedResponse.text()).toBe('catalog');
		expect(securedResponse.headers.get('Content-Security-Policy')).toBe(
			"base-uri 'self'; form-action 'self'; frame-ancestors 'none'"
		);
		expect(securedResponse.headers.get('Cross-Origin-Opener-Policy')).toBe('same-origin');
		expect(securedResponse.headers.get('Permissions-Policy')).toBe(
			'camera=(), geolocation=(), microphone=(), payment=(), usb=()'
		);
		expect(securedResponse.headers.get('Referrer-Policy')).toBe('strict-origin-when-cross-origin');
		expect(securedResponse.headers.get('Strict-Transport-Security')).toBe(
			'max-age=31536000; includeSubDomains'
		);
		expect(securedResponse.headers.get('X-Content-Type-Options')).toBe('nosniff');
		expect(securedResponse.headers.get('X-Frame-Options')).toBe('DENY');
		expect(securedResponse.headers.get('X-Existing')).toBe('preserved');
	});

	it('preserves the stronger CSP generated by SvelteKit', () => {
		const generatedPolicy =
			"default-src 'self'; script-src-attr 'none'; object-src 'none'; frame-ancestors 'none'";
		const response = new Response('catalog', {
			headers: { 'Content-Security-Policy': generatedPolicy }
		});

		const securedResponse = applySecurityHeaders(response);

		expect(securedResponse.headers.get('Content-Security-Policy')).toBe(generatedPolicy);
	});
});
